language: rust
rust:
- nightly
cache: cargo
script:
  - cargo build --verbose --release

deploy:
  provider: heroku
  api_key:
    secure: d5NnC1Zn7u4nPK/zzm99i7pZtLog9f5s3GFJm9Abci2vcZGXB4zgOm+rBVm1ZZLt1t5FgRUdUTi75FMCguZUy2pU7oO9gA4o94+eA+YvCXzKrpx9AYEpz+wd86ziNkc46Cf7kR5Q0I6zFZy0B6KhaA3WuvLcZVa8fwPlQIyKDUEMV7hrYaF0fueR6FKJiRXBtc4zWa39y9n6MstGyJrG9MpKEl92skQtSWSQFobk0hiRFloy8qL7bV0Cg/37Jr2rBS0wbHlyENHDLcuY7mKXBRoLt3cbrl8sOd6qlWY4o1zaAfuD+ZxtVohIb9tR+UyqQZcuCQjaZ2lHbjbS1QStyhOUuIOh2BJYslYxaV42u7Q7mAhEEcF8GfB9jBpYYFzCSCTIL00gFT1W1PTHLSp1RssV501abyA5OmpdmMP220efd396kFjULsOnjrnRUP/eld/lLwta5dMjheOMG6zDgFlunsqaojn/qJEt6RKyfDjjI+zXKT5KdzWIthfnwobsaPZIVnkV1VHfePAoT7qMwCRJgT5imZgAlfoqJXO55haw9HSzfaVg2tUEzyneXIQNredJfgSTphO+d9Cvlu3kDXMBca89OLQvMOvK96tBNfmfJ56xknUsnKnEb3tYp4++MT2ebxcb62ZFrLWQ6pe2PhLEfksEupzrpOFGo4DkjB4=

notifications:
  email: false