language: rust
cache: cargo
script:
- cargo build --verbose --release
deploy:
  provider: heroku
  api_key:
    secure: t2jSIEI38IIKsZIj7H2544Fnctoxjxv2TrY3LVmGgqQWc9GS7heAlODFu6i68ZPWwKANmZvbHhneQqFd0BN2CPwSu3tfh3phmUlK1ZCaaAcL2ZzASgmUpLOA8QtKSkQBOJU1Zth5WK21FRHtP7Z26ladv3wi+26D/3ntNKrirJG6AH/ze2Ed55R5zeIeEiVKsvmqlIJFLuV+69WGS4Piw0Sznfn9QwYS+LRYAZX0NBi/2hYKmwLUqRUljeCZ4aVIXI3aiayJlw8CFNlysEjYbmVy9Wiwbhvjv4teG3/8yOuEYcWhnNUMVE0tbIT1p/hfqRVZOhQSoE2itXFjXe5nEJtGW2oo3AX9asNQqW4+CpROkCgmEiF62ODRr7s2xpHBQC1UnNzWiJf75iN0PSsz5u8TE9XQAzzZAdDAu1rxTjEf4zfxo7K98ctwQlfSzlEjOIsJQMKfTNX0Q4+3LVX1CsZ8ypGEJ4Q1lDSK6Y5gf42og5aGhJLMbwKMjPk7hsnYvkAuFgJ5WiLNpEm37Hz6nT5Wb9C4SxLCdb9ONNQa1YfmFXTlQaP+wIsWyDYLk2IPBHSda3VQXd1lHoAxv+Ctoe2F5jLxr+D6aaDYJa7DFn6Y1G9pR1PsAMv/U7SSxVqUqeO/qoKF6XORIbDOhC6Sp/NLzI9D4VHs+yVd6psS1HY=
notifications:
  email: false
