language: rust
rust:
- nightly
cache: cargo
script:
- cargo build --verbose --release

deploy:
  provider: heroku
  api_key:
    secure: Fr1jxdgsK3be/TwpACe8hyzz0WZ6tjY/lneyFvJVYawn0Gtnto+e7cnyigVNcvf0q4tbXTUZQKYKU6hGf/+1zQcDF4r9UyB2b6SH23810nH6rJxv/+l8uBM0c2RCa+5rkjZl84TDjWGLMAkRhFueH5xLY6tR6Gk64lel18BCeh37UF3qSmkpIPFVRC7RS3ojZHm5LnIUAcsuT724oa3O8RBNC/te9y9cyBToIib7fetJDrJo2ZGhfBaQW0ejepOTZvb1n7P6G2k6PaP5S/oU64VEORLuuaJu72s04gpc1V8BcfbW+9YDiuaIPI9VIAfbYW3u7Q4CUb2t9BOOA/GMFEW+GpeRTl3hpQoIGrY73AXhM/2VSLzNaTYa71edQ+Owc9TTkmVCIgY1UIwVTF70gi2MOZ/XXhaq+aWO5wPyUq0B5XQlpPxlXkajbBcOj+9krgiQjnQKenl6ouXXxQuXIHYiMDV4hzIxd8HBtLMUMU7nu7ceJBx67kT3LtbWk48Ep/4sRc7IrNnZPxDysaGy0xIYmR49Nq1VILHhQ7nd77nBuEIOp8CZExTv07du0QhomkAowiwUNbJFoBpPIvHORf61zBOOIqiQPt80vpTU+S50HPeNSarR7ivFPgo6Ct9e6GWAvnl4dDEa56BAr5cQFqZb27hNR3HHe4Hf2ruDwRg=
notifications:
  email: false
